account/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from account.views import RegisterView, ProfileView, ProfileList, logout_view, SubscribeView, UnsubscribeView

app_name = 'account'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', logout_view, name='logout'),
    path('registration/', RegisterView.as_view(), name='registration'),
    path('<int:pk>/profile/', ProfileView.as_view(), name='profile'),
    path('profile/users/', ProfileList.as_view(), name='profile_list'),
    path('subscribe/<int:user_id>/', SubscribeView.as_view(), name='subscribe'),
    path('unsubscribe/<int:user_id>/', UnsubscribeView.as_view(), name='unsubscribe'),
]

api_v1/urls.py
from django.urls import path, include
from rest_framework import routers
from api_v1.views import PostViewSet
from rest_framework.authtoken.views import obtain_auth_token
from django.contrib.auth.views import LogoutView

app_name = 'api_v1'

router = routers.DefaultRouter()
router.register(r'posts', PostViewSet)
# router.register('')

urlpatterns = [
    path('', include(router.urls)),
    path('login/', obtain_auth_token, name='api_token_auth'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

instagram2/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('apps.account.urls')),
    path('', include('apps.webapp.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.urls import path

from webapp.views.comment import CommentAddView, CommentDeleteView
from webapp.views.post import PostListView, PostAddView, PostDeleteView, PostUpdateView, PostLikeView, PostDetailView

app_name = 'webapp'
urlpatterns = [
    path('', PostListView.as_view(), name='posts'),
    path('post/add', PostAddView.as_view(), name='post_add'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post_update'),
    path('post/<int:post_id>/like/', PostLikeView.as_view(), name='like_post'),
    path('post/<int:pk>/comment/add', CommentAddView.as_view(), name='comment_add'),
    path('post/<int:pk>/view', PostDetailView.as_view(), name='post_comment_view'),
    path('post/<int:post_pk>/comment/<int:comment_pk>/delete/', CommentDeleteView.as_view(), name='comment_delete')

]

instagram2/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
    {% block title %}
        <title>Document</title>
    {% endblock %}

    <style>
        {% block style %}

        {% endblock %}
    </style>
</head>
<body>
<nav class="navbar navbar-expand-lg bg-body-white mb-3">
    <div class="container-fluid">
        <a href="{% url 'webapp:posts' %}"> <img src="{% static 'logo.jpeg' %}" alt="logo" style="width: 150px"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        {% if request.user.is_authenticated %}
            <form class="d-flex" role="search" method="get" action="{% url 'account:profile_list' %}">
                <input class="form-control me-2" type="search" placeholder="Search" name="search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Поиск</button>
            </form>
        {% endif %}

        {% if request.user.is_authenticated %}
            <div class="d-flex ms-auto align-items-center">
                <ul class="navbar-nav me-3">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'webapp:post_add' %}">
                            <i class="bi bi-plus-square" style="font-size: 25px;"></i>
                        </a>
                    </li>
                </ul>
                <div class="profile">
                    <div class="dropdown ms-auto">
                        <a href="#" id="dropdownMenuButton" data-bs-toggle="dropdown" role="button"
                           aria-expanded="false" style="text-decoration: none; color: black;">
                            <i class="bi bi-person" style="font-size: 35px;"></i><br>
                            <small>{{ request.user }}</small><br>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton">
                            <li><a class="dropdown-item"
                                   href="{% url 'account:profile' request.user.pk %}">Профиль</a></li>
                            <li><a class="dropdown-item" href="{% url 'account:logout' %}">Выйти</a></li>
                        </ul>
                    </div>

                </div>
            </div>
        {% else %}
            <div class=" profile ms-auto">
                <a href="{% url 'account:login' %}"
                   style="text-decoration: none; color: black; text-align: center;">
                    <big>
                        <i class="bi bi-person" style="font-size: 25px;"></i>
                    </big><br>
                </a>
            </div>
        {% endif %}
    </div>
</nav>

<div class="container">
    {% block content %}
    {% endblock %}
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>
</html>