account/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from account.views import RegisterView, ProfileView, ProfileList, logout_view, SubscribeView, UnsubscribeView

app_name = 'account'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', logout_view, name='logout'),
    path('registration/', RegisterView.as_view(), name='registration'),
    path('<int:pk>/profile/', ProfileView.as_view(), name='profile'),
    path('profile/users/', ProfileList.as_view(), name='profile_list'),
    path('subscribe/<int:user_id>/', SubscribeView.as_view(), name='subscribe'),
    path('unsubscribe/<int:user_id>/', UnsubscribeView.as_view(), name='unsubscribe'),
]

api_v1/urls.py
from django.urls import path, include
from rest_framework import routers
from api_v1.views import PostViewSet
from rest_framework.authtoken.views import obtain_auth_token
from django.contrib.auth.views import LogoutView

app_name = 'api_v1'

router = routers.DefaultRouter()
router.register(r'posts', PostViewSet)
# router.register('')

urlpatterns = [
    path('', include(router.urls)),
    path('login/', obtain_auth_token, name='api_token_auth'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

apps/webapp/urls.py
from django.urls import path

from apps.webapp.views.comment import CommentAddView, CommentDeleteView
from apps.webapp.views.post import PostListView, PostAddView, PostDeleteView, PostUpdateView, PostLikeView, PostDetailView

app_name = 'webapp'
urlpatterns = [
    path('', PostListView.as_view(), name='posts'),
    path('post/add', PostAddView.as_view(), name='post_add'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post_update'),
    path('post/<int:post_id>/like/', PostLikeView.as_view(), name='like_post'),
    path('post/<int:pk>/comment/add', CommentAddView.as_view(), name='comment_add'),
    path('post/<int:pk>/view', PostDetailView.as_view(), name='post_comment_view'),
    path('post/<int:post_pk>/comment/<int:comment_pk>/delete/', CommentDeleteView.as_view(), name='comment_delete')

]

instagram2/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('apps.account.urls')),
    path('', include('apps.webapp.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.urls import path

from webapp.views.comment import CommentAddView, CommentDeleteView
from webapp.views.post import PostListView, PostAddView, PostDeleteView, PostUpdateView, PostLikeView, PostDetailView

app_name = 'webapp'
urlpatterns = [
    path('', PostListView.as_view(), name='posts'),
    path('post/add', PostAddView.as_view(), name='post_add'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post_update'),
    path('post/<int:post_id>/like/', PostLikeView.as_view(), name='like_post'),
    path('post/<int:pk>/comment/add', CommentAddView.as_view(), name='comment_add'),
    path('post/<int:pk>/view', PostDetailView.as_view(), name='post_comment_view'),
    path('post/<int:post_pk>/comment/<int:comment_pk>/delete/', CommentDeleteView.as_view(), name='comment_delete')

]

apps/webapp/models/comments.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

User = get_user_model()


class Comment(models.Model):
    comment = models.CharField(max_length=300, verbose_name="Комментарий")
    post = models.ForeignKey('Post', on_delete=models.CASCADE, verbose_name='Пост', related_name='comment')
    author = models.ForeignKey(User, related_name="comments", on_delete=models.CASCADE)

    def __str__(self):
        return self.comment

    class Meta:
        db_table = "comment"
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"

apps/webapp/models/post.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Post(models.Model):
    image = models.ImageField(upload_to='post/', verbose_name='Изображение')
    summary = models.CharField(max_length=500, blank=True, verbose_name='Описание')
    likes_count = models.PositiveIntegerField(default=0)
    comments_count = models.PositiveIntegerField(default=0)
    author = models.ForeignKey(User, related_name="posts", on_delete=models.CASCADE)
    created_at = models.DateField(auto_now_add=True, verbose_name='Дата публикации')
    liked_by = models.ManyToManyField(User, related_name='liked_posts', blank=True)

    def __str__(self):
        return self.summary[:30]

    class Meta:
        db_table = 'posts'
        verbose_name = 'пост'
        verbose_name_plural = 'посты'

apps/webapp/forms/comment.py
from django import forms

from apps.webapp.models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']

apps/webapp/forms/like.py
from django import forms

class LikeForm(forms.Form):
    post_id = forms.IntegerField(widget=forms.HiddenInput())

apps/webapp/forms/post.py
from django import forms

from apps.webapp.models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['image', 'summary']

webapp/forms/comment.py
from django import forms

from webapp.models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']

webapp/forms/post.py
from django import forms

from webapp.models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['image', 'summary']

apps/webapp/views/comment.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView
from apps.webapp.forms.comment import CommentForm
from apps.webapp.models import Comment, Post


class CommentAddView(LoginRequiredMixin, CreateView):
    template_name = 'comment_templates/comment_add.html'
    model = Comment
    form_class = CommentForm
    success_url = 'webapp:posts'

    def form_valid(self, form):
        form.instance.author = self.request.user
        pk = self.kwargs.get('pk')
        post = get_object_or_404(Post, id=pk)
        form.instance.post = post



        return super().form_valid(form)

    def get_success_url(self):
        pk = self.kwargs.get('pk')
        return reverse_lazy('webapp:post_comment_view', kwargs={'pk': pk})


class CommentDeleteView(LoginRequiredMixin, DeleteView):
    model = Comment
    template_name = 'comment_templates/comment_delete.html'
    # success_url = ('webapp:posts')

    def get_object(self, queryset=None):
        post_pk = self.kwargs.get('post_pk')
        comment_pk = self.kwargs.get('comment_pk')
        return get_object_or_404(Comment, pk=comment_pk, post_id=post_pk)


    def get_success_url(self):
        post_pk = self.kwargs.get('post_pk')
        return reverse_lazy('webapp:post_comment_view', kwargs={'pk': post_pk})

apps/webapp/views/post.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import ListView, CreateView, DeleteView, UpdateView, DetailView

from apps.account.models import Profile
from apps.webapp.forms.comment import CommentForm
from apps.webapp.forms.like import LikeForm
from apps.webapp.forms.post import PostForm
from apps.webapp.models import Post

User = get_user_model()


# Create your views here.

class PostListView(LoginRequiredMixin, ListView):
    template_name = 'post_templates/posts.html'
    model = Post
    context_object_name = 'posts'
    ordering = "-created_at"

    # def get_queryset(self):
    #     user = self.request.user
    #     if not hasattr(user, 'profile'):
    #         return Post.objects.none()
    #
    #     followed_profiles = Profile.objects.filter(following__follower=user.profile)
    #
    #     # queryset = Post.objects.filter(author__in=followed_profiles).order_by('-created_at')
    #     return queryset

    def get_queryset(self):
        return Post.objects.all().order_by('-created_at')


class PostAddView(LoginRequiredMixin, CreateView):
    template_name = 'post_templates/post_add.html'
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('webapp:posts')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'post_templates/post_delete.html'
    model = Post
    success_url = reverse_lazy('webapp:posts')


class PostUpdateView(UpdateView):
    template_name = 'post_templates/post_update.html'
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('webapp:posts')


class PostDetailView(LoginRequiredMixin, DetailView):
    template_name = 'post_templates/post_view.html'
    context_object_name = 'post'
    model = Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = self.get_object()
        context['comments'] = post.comment.all()
        context['form'] = CommentForm()
        return context


class PostLikeView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        post_id = kwargs.get('pk')
        form = LikeForm(request.POST)
        if form.is_valid():
            post_id = form.cleaned_data.get('post_id')
            post = get_object_or_404(Post, id=post_id)

        if request.user not in post.liked_by.all():
            post.liked_by.add(request.user)
            post.likes_count += 1
            post.save()
        else:
            post.liked_by.remove(request.user)
            post.likes_count -= 1
            post.save()

        return redirect('webapp:post_comment_view', pk=post_id)

webapp/views/comment.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView
from webapp.forms.comment import CommentForm
from webapp.models import Comment, Post


class CommentAddView(LoginRequiredMixin, CreateView):
    template_name = 'comment_templates/comment_add.html'
    model = Comment
    form_class = CommentForm
    success_url = 'webapp:posts'

    def form_valid(self, form):
        form.instance.author = self.request.user
        pk = self.kwargs.get('pk')
        post = get_object_or_404(Post, id=pk)
        form.instance.post = post
        return super().form_valid(form)

    def get_success_url(self):
        pk = self.kwargs.get('pk')
        return reverse_lazy('webapp:post_comment_view', kwargs={'pk': pk})


class CommentDeleteView(LoginRequiredMixin, DeleteView):
    model = Comment
    template_name = 'comment_templates/comment_delete.html'
    success_url = reverse_lazy('webapp:posts')

    def get_object(self, queryset=None):
        post_pk = self.kwargs.get('post_pk')
        comment_pk = self.kwargs.get('comment_pk')
        return get_object_or_404(Comment, pk=comment_pk, post_id=post_pk)

webapp/views/post.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import ListView, CreateView, DeleteView, UpdateView, DetailView

from account.models import Profile
from webapp.forms.comment import CommentForm
from webapp.forms.like import LikeForm
from webapp.forms.post import PostForm
from webapp.models import Post

User = get_user_model()


# Create your views here.

class PostListView(LoginRequiredMixin, ListView):
    template_name = 'post_templates/posts.html'
    model = Post
    context_object_name = 'posts'
    ordering = "-created_at"

    class PostListView(LoginRequiredMixin, ListView):
        template_name = 'post_templates/posts.html'
        model = Post
        context_object_name = 'posts'
        ordering = "-created_at"

        def get_queryset(self):
            user = self.request.user
            if not hasattr(user, 'profile'):
                return Post.objects.none()

            followed_profiles = Profile.objects.filter(following__follower=user.profile)

            queryset = Post.objects.filter(author__in=followed_profiles).order_by('-created_at')

            return queryset


class PostAddView(LoginRequiredMixin, CreateView):
    template_name = 'post_templates/post_add.html'
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('webapp:posts')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'post_templates/post_delete.html'
    model = Post
    success_url = reverse_lazy('webapp:posts')


class PostUpdateView(UpdateView):
    template_name = 'post_templates/post_update.html'
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('webapp:posts')


class PostDetailView(LoginRequiredMixin, DetailView):
    template_name = 'post_templates/post_view.html'
    context_object_name = 'post'
    model = Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = self.get_object()
        context['comments'] = post.comment.all()
        context['form'] = CommentForm()
        return context


class PostLikeView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        post_id = kwargs.get('pk')
        form = LikeForm(request.POST)
        if form.is_valid():
            post_id = form.cleaned_data.get('post_id')
            post = get_object_or_404(Post, id=post_id)

            if request.user not in post.liked_by.all():
                post.liked_by.add(request.user)
                post.likes_count += 1
                post.save()
            else:
                post.liked_by.remove(request.user)
                post.likes_count -= 1
                post.save()

        return redirect('webapp:post_comment_view', pk=post_id)

apps/webapp/templates/post_templates/post_add.html
{% extends 'base.html' %}

{% block title %}

{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data" class="text-center">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Добавить</button>
    </form>
{% endblock %}

apps/webapp/templates/post_templates/post_delete.html
{% extends 'base.html' %}

{% block title %}
    <title>Удалить пост</title>
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Delete</button>
        <a href="{% url 'webapp:posts' %}" class="btn btn-primary">Cancel</a>
    </form>
{% endblock %}

apps/webapp/templates/post_templates/post_update.html
{% extends 'base.html' %}

{% block title %}

{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Изменить</button>
    </form>
{% endblock %}

apps/webapp/templates/post_templates/post_view.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>{{ post.author.username }}'s post</title>
{% endblock %}

{% block content %}
<div class="container mt-4 d-flex justify-content-center">
    <div class="post-detail row" style="max-width: 900px; border: 1px solid #dbdbdb; border-radius: 10px;">
        <div class="col-md-7 p-0" style="border-right: 1px solid #dbdbdb;">
            <img src="{{ post.image.url }}" alt="{{ post.summary }}" class="img-fluid w-100" style="max-height: 700px;">
        </div>

        <div class="col-md-5 d-flex flex-column justify-content-between">
            <div class="p-3" style="border-bottom: 1px solid #dbdbdb;">
                <div class="d-flex align-items-center">
                    <div>
                        {% if post.author.avatar %}
                            <a href="{% url 'account:profile' post.author.id %}">
                                <img src="{{ post.author.avatar.url }}" alt="avatar"
                                     style="width: 40px; height: 40px; border-radius: 50%;">
                            </a>
                        {% else %}
                            <a href="{% url 'account:profile' post.author.id %}">
                                <img src="{% static 'img.png' %}" alt="avatar"
                                     style="width: 40px; height: 40px; border-radius: 50%;">
                            </a>
                        {% endif %}
                    </div>
                    <div class="ms-3">
                        <a href="{% url 'account:profile' post.author.id %}"
                           class="text-dark text-decoration-none">
                            <strong>{{ post.author.username }}</strong>
                        </a>
                        <p class="mb-0 text-muted" style="font-size: 12px;">Ciudad Real Madrid</p>
                    </div>
                </div>
            </div>

            <div class="comments-section p-3 flex-grow-1" style="overflow-y: auto; max-height: 500px;">
                {% if comments %}
                    {% for comment in comments %}
                        <div class="d-flex align-items-start mb-3">
                            <div>
                                {% if comment.author.avatar %}
                                    <a href="{% url 'account:profile' comment.author.id %}">
                                        <img src="{{ comment.author.avatar.url }}" alt="avatar"
                                             style="width: 30px; height: 30px; border-radius: 50%;">
                                    </a>
                                {% else %}
                                    <a href="{% url 'account:profile' comment.author.id %}">
                                        <img src="{% static 'img.png' %}" alt="avatar"
                                             style="width: 30px; height: 30px; border-radius: 50%;">
                                    </a>
                                {% endif %}
                            </div>
                            <div class="ms-2">
                                <p class="mb-0">
                                    <a href="{% url 'account:profile' comment.author.id %}"
                                       class="text-dark text-decoration-none">
                                        <strong>{{ comment.author.username }}</strong>
                                    </a>
                                    {{ comment.comment }}
                                </p>
                                <p class="text-muted mb-0" style="font-size: 12px;">
                                    {{ comment.created_at|date:"d M Y H:i" }}
                                </p>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <p class="text-muted">No comments yet.</p>
                {% endif %}
            </div>

            <div class="p-3">
                <div class="mb-3">
                    <div class="d-flex align-items-center mb-2">
                        <form method="post" action="{% url 'webapp:like_post' post.id %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-link p-0 text-danger">
                                <i class="bi bi-heart{% if request.user in post.liked_by.all %}-fill{% endif %}"></i>
                            </button>
                        </form>
                        <span class="ms-2"><strong>{{ post.likes_count }}</strong> likes</span>
                    </div>
                    <p><strong>{{ post.author.username }}</strong> {{ post.summary }}</p>
                    <p class="text-muted" style="font-size: 12px;">{{ post.created_at|date:"Y-m-d" }}</p>
                </div>

                <form action="{% url 'webapp:comment_add' post.id %}" method="post">
                    {% csrf_token %}
                    <div class="d-flex">
                        <textarea name="comment" rows="1" class="form-control me-2"
                                  placeholder="Add a comment..." style="resize: none;"></textarea>
                        <button type="submit" class="btn btn-primary">Post</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

apps/webapp/templates/post_templates/posts.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Posts</title>
{% endblock %}

{% block content %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-lg-6">
{#                <p class="text-center mb-4">Number of posts: {{ posts.count }}</p>#}
                {% for post in posts %}
                    <div class="card mb-4 border-0">
                        <div class="card-body p-3">
                            <div class="d-flex align-items-center mb-3">
                                {% if post.author.avatar %}
                                    <a href="{% url 'account:profile' post.author.pk %}">
                                        <img src="{{ post.author.avatar.url }}" class="avatar me-3" alt="pfp"
                                             style="height: 32px; width: 32px; border-radius: 50%; object-fit: cover;">
                                    </a>
                                {% else %}
                                    <a href="{% url 'account:profile' post.author.pk %}">
                                        <img src="{% static 'img.png' %}" class="avatar me-3" alt="pfp"
                                             style="height: 32px; width: 32px; border-radius: 50%; object-fit: cover;">
                                    </a>
                                {% endif %}
                                <a href="{% url 'account:profile' post.author.pk %}" style="text-decoration: none; color: black;">
                                    <h5 class="card-title mb-0">{{ post.author.username }}</h5>
                                </a>
                                {% if post.author.pk == request.user.pk %}
                                    <div class="dropdown ms-auto">
                                        <button class="btn btn-link" type="button" id="dropdownMenuButton"
                                                data-bs-toggle="dropdown" aria-expanded="false">
                                            <i class="bi bi-three-dots"></i>
                                        </button>
                                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                            <li><a class="dropdown-item" href="{% url 'webapp:post_update' post.pk %}">Edit Post</a></li>
                                            <li><a class="dropdown-item" href="{% url 'webapp:post_delete' post.pk %}">Delete Post</a></li>
                                        </ul>
                                    </div>
                                {% endif %}
                            </div>
                            <a href="{% url 'webapp:post_comment_view' post.pk %}">
                                <img src="{{ post.image.url }}" class="card-img-top mb-3" alt="Post Image"
                                     style="width: 100%; height: auto; max-height: 600px; object-fit: cover;">
                            </a>
                            <p class="card-text">{{ post.summary }}</p>
                        </div>
                        <div class="card-footer p-2 d-flex justify-content-between align-items-center">
                            <div class="d-flex align-items-center">
                                <form method="post" action="{% url 'webapp:like_post' post.id %}">
                                    {% csrf_token %}
                                    <input type="hidden" name="post_id" value="{{ post.id }}">
                                    <button type="submit" class="btn btn-link text-danger p-0">
                                        <i class="bi bi-heart{% if request.user in post.liked_by.all %}-fill{% endif %}"></i>
                                    </button>
                                    <span class="ms-2">{{ post.likes_count }} Likes</span>
                                </form>
                            </div>
                            <div class="ms-3">
                                <a href="{% url 'webapp:post_comment_view' post.pk %}" style="text-decoration: none; color: black;">
                                    <i class="bi bi-chat-dots"></i> {{ post.comments_count }} Comments
                                </a>
                            </div>
                            <div class="ms-auto text-muted">
                                <small>{{ post.created_at|date:'Y-m-d' }}</small>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}