account/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from account.views import RegisterView, ProfileView, ProfileList, logout_view, SubscribeView, UnsubscribeView

app_name = 'account'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', logout_view, name='logout'),
    path('registration/', RegisterView.as_view(), name='registration'),
    path('<int:pk>/profile/', ProfileView.as_view(), name='profile'),
    path('profile/users/', ProfileList.as_view(), name='profile_list'),
    path('subscribe/<int:user_id>/', SubscribeView.as_view(), name='subscribe'),
    path('unsubscribe/<int:user_id>/', UnsubscribeView.as_view(), name='unsubscribe'),
]

api_v1/urls.py
from django.urls import path, include
from rest_framework import routers
from api_v1.views import PostViewSet
from rest_framework.authtoken.views import obtain_auth_token
from django.contrib.auth.views import LogoutView

app_name = 'api_v1'

router = routers.DefaultRouter()
router.register(r'posts', PostViewSet)
# router.register('')

urlpatterns = [
    path('', include(router.urls)),
    path('login/', obtain_auth_token, name='api_token_auth'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

apps/account/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from apps.account.views import RegisterView, ProfileView, ProfileList, logout_view, SubscribeView, UnsubscribeView

app_name = 'account'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='../templates/login.html'), name='login'),
    path('logout/', logout_view, name='logout'),
    path('registration/', RegisterView.as_view(), name='registration'),
    path('<int:pk>/profile/', ProfileView.as_view(), name='profile'),
    path('profile/users/', ProfileList.as_view(), name='profile_list'),
    path('subscribe/<int:user_id>/', SubscribeView.as_view(), name='subscribe'),
    path('unsubscribe/<int:user_id>/', UnsubscribeView.as_view(), name='unsubscribe'),
]

instagram2/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('apps.account.urls')),
    path('', include('apps.webapp.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.urls import path

from webapp.views.comment import CommentAddView, CommentDeleteView
from webapp.views.post import PostListView, PostAddView, PostDeleteView, PostUpdateView, PostLikeView, PostDetailView

app_name = 'webapp'
urlpatterns = [
    path('', PostListView.as_view(), name='posts'),
    path('post/add', PostAddView.as_view(), name='post_add'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post_update'),
    path('post/<int:post_id>/like/', PostLikeView.as_view(), name='like_post'),
    path('post/<int:pk>/comment/add', CommentAddView.as_view(), name='comment_add'),
    path('post/<int:pk>/view', PostDetailView.as_view(), name='post_comment_view'),
    path('post/<int:post_pk>/comment/<int:comment_pk>/delete/', CommentDeleteView.as_view(), name='comment_delete')

]

apps/account/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.


genders = [("M", 'Male'), ("F", 'Female')]


class Profile(AbstractUser):
    avatar = models.ImageField(upload_to='avatars/', verbose_name="Аватарка")
    phone_num = models.CharField(max_length=20, blank=True, null=True, verbose_name='Номер телефона')
    bio = models.CharField(max_length=70, blank=True, null=True, verbose_name='Информация о пользователе')
    gender = models.CharField(max_length=25, choices=genders, blank=True, null=True)
    posts_count = models.PositiveIntegerField(default=0)
    followers_count = models.PositiveIntegerField(default=0)
    following_count = models.PositiveIntegerField(default=0)

    followers = models.ManyToManyField('self', through='Subscription', symmetrical=False, related_name='following')

    groups = models.ManyToManyField('auth.Group', related_name='profile_user_set', blank=True, verbose_name='groups')
    user_permissions = models.ManyToManyField(
        'auth.Permission', related_name='profile_user_set', blank=True, verbose_name='user permissions')

    def __str__(self):
        return self.username

    class Meta:
        db_table = "profile"
        verbose_name = 'профиль'
        verbose_name_plural = "профили"

class Subscription(models.Model):
    follower = models.ForeignKey(Profile, related_name='follower_set', on_delete=models.CASCADE)
    following = models.ForeignKey(Profile, related_name='following_set', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('follower', 'following')

account/forms.py
from django import forms
from django.contrib.auth import get_user_model

from account.models import Profile

User = get_user_model()


class UserRegistrationForm(forms.ModelForm):
    username = forms.CharField(max_length=16, required=True, label='Имя пользователя')
    email = forms.EmailField(widget=forms.EmailInput, required=True)
    password = forms.CharField(label='Пароль', strip=False, required=True, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label='Потвердить пароль', strip=False, required=True,
                                       widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()
        self.validate_username_length()
        password = self.cleaned_data.get("password")
        password_confirm = self.cleaned_data.get("password_confirm")

        if password != password_confirm:
            raise forms.ValidationError("Пароли не совпадают!")
        return self.cleaned_data

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

    def validate_username_length(self):
        username = self.cleaned_data.get('username')
        if username and not 2 <= len(username) <= 16:
            raise forms.ValidationError("Имя пользователя должно содержать от 4 до 16 символов.")

    class Meta:
        model = Profile
        fields = ['username', 'email', 'avatar', 'password', 'password_confirm', 'first_name', 'bio', 'phone_num',
                  'gender']


class SearchForm(forms.Form):
    search = forms.CharField(max_length=20, label="Поиск", required=False)

apps/account/forms.py
from django import forms
from django.contrib.auth import get_user_model

from apps.account.models import Profile

User = get_user_model()


class UserRegistrationForm(forms.ModelForm):
    username = forms.CharField(max_length=16, required=True, label='Имя пользователя')
    email = forms.EmailField(widget=forms.EmailInput, required=True)
    password = forms.CharField(label='Пароль', strip=False, required=True, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label='Потвердить пароль', strip=False, required=True,
                                       widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()
        self.validate_username_length()
        password = self.cleaned_data.get("password")
        password_confirm = self.cleaned_data.get("password_confirm")

        if password != password_confirm:
            raise forms.ValidationError("Пароли не совпадают!")
        return self.cleaned_data

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

    def validate_username_length(self):
        username = self.cleaned_data.get('username')
        if username and not 2 <= len(username) <= 16:
            raise forms.ValidationError("Имя пользователя должно содержать от 4 до 16 символов.")

    class Meta:
        model = Profile
        fields = ['username', 'email', 'avatar', 'password', 'password_confirm', 'first_name', 'bio', 'phone_num',
                  'gender']


class SearchForm(forms.Form):
    search = forms.CharField(max_length=20, label="Поиск", required=False)

account/views.py
from django.contrib.auth import login, logout, get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse
from django.views import View
from django.views.generic import CreateView, DetailView, ListView

from account.forms import UserRegistrationForm, SearchForm
from account.models import Profile, Subscription
from webapp.models import Post

User = get_user_model()


def logout_view(request):
    logout(request)
    return redirect('webapp:posts')


class RegisterView(CreateView):
    template_name = 'registration.html'
    form_class = UserRegistrationForm
    model = User

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if not next_url:
            next_url = self.request.POST.get('next')
        if not next_url:
            next_url = reverse('webapp:posts')
        return next_url


class ProfileView(LoginRequiredMixin, DetailView):
    template_name = 'profile_view.html'
    model = Profile
    context_object_name = 'user_obj'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profile = self.object
        context['posts'] = Post.objects.filter(author=profile)
        context['posts_count'] = profile.posts_count
        context['followers_count'] = profile.followers_count
        context['following_count'] = profile.following_count
        context['is_subscribed'] = self.request.user.following.filter(id=profile.id).exists()
        return context


class ProfileList(ListView):
    template_name = 'profiles_list.html'
    model = Profile
    context_object_name = 'profiles'

    def dispatch(self, request, *args, **kwargs):
        self.form = self.get_form()
        self.search_value = self.get_search_value()
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            queryset = queryset.filter(
                Q(username__icontains=self.search_value) | Q(email__icontains=self.search_value) | Q(
                    first_name__icontains=self.search_value)
            )
        return queryset

    def get_form(self):
        return SearchForm(self.request.GET)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_form'] = self.form
        context['search_value'] = self.search_value
        return context

    def get_search_value(self):
        form = self.form
        if form.is_valid():
            return form.cleaned_data['search']
        return None


class SubscribeView(LoginRequiredMixin, View):
    def post(self, request, user_id):
        user_to_subscribe = get_object_or_404(Profile, id=user_id)

        if request.user != user_to_subscribe:
            subscription, created = Subscription.objects.get_or_create(follower=request.user, following=user_to_subscribe)
            if created:
                request.user.following_count += 1
                user_to_subscribe.followers_count += 1
                request.user.save()
                user_to_subscribe.save()

        return HttpResponseRedirect(reverse('account:profile', args=[user_id]))


class UnsubscribeView(LoginRequiredMixin, View):
    def post(self, request, user_id):
        user_to_unfollow = get_object_or_404(Profile, id=user_id)
        if request.user != user_to_unfollow:
            subscription = Subscription.objects.filter(follower=request.user, following=user_to_unfollow).first()

            if subscription:
                subscription.delete()
                request.user.following_count -= 1
                user_to_unfollow.followers_count -= 1
                request.user.save()
                user_to_unfollow.save()

        return HttpResponseRedirect(reverse('account:profile', args=[user_id]))

apps/account/views.py
from django.contrib.auth import login, logout, get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse
from django.views import View
from django.views.generic import CreateView, DetailView, ListView

from apps.account.forms import UserRegistrationForm, SearchForm
from apps.account.models import Profile, Subscription
from apps.webapp.models import Post

User = get_user_model()


def logout_view(request):
    logout(request)
    return redirect('webapp:posts')


class RegisterView(CreateView):
    template_name = 'registration.html'
    form_class = UserRegistrationForm
    model = User

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if not next_url:
            next_url = self.request.POST.get('next')
        if not next_url:
            next_url = reverse('webapp:posts')
        return next_url


class ProfileView(LoginRequiredMixin, DetailView):
    template_name = 'profile_view.html'
    model = Profile
    context_object_name = 'user_obj'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profile = self.object
        context['posts'] = Post.objects.filter(author=profile)
        context['posts_count'] = profile.posts_count
        context['followers_count'] = profile.followers_count
        context['following_count'] = profile.following_count
        context['is_subscribed'] = self.request.user.following.filter(id=profile.id).exists()
        return context


class ProfileList(ListView):
    template_name = 'profiles_list.html'
    model = Profile
    context_object_name = 'profiles'

    def dispatch(self, request, *args, **kwargs):
        self.form = self.get_form()
        self.search_value = self.get_search_value()
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            queryset = queryset.filter(
                Q(username__icontains=self.search_value) | Q(email__icontains=self.search_value) | Q(
                    first_name__icontains=self.search_value)
            )
        return queryset

    def get_form(self):
        return SearchForm(self.request.GET)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_form'] = self.form
        context['search_value'] = self.search_value
        return context

    def get_search_value(self):
        form = self.form
        if form.is_valid():
            return form.cleaned_data['search']
        return None


class SubscribeView(LoginRequiredMixin, View):
    def post(self, request, user_id):
        user_to_subscribe = get_object_or_404(Profile, id=user_id)

        if request.user != user_to_subscribe:
            subscription, created = Subscription.objects.get_or_create(follower=request.user, following=user_to_subscribe)
            if created:
                request.user.following_count += 1
                user_to_subscribe.followers_count += 1
                request.user.save()
                user_to_subscribe.save()

        return HttpResponseRedirect(reverse('account:profile', args=[user_id]))


class UnsubscribeView(LoginRequiredMixin, View):
    def post(self, request, user_id):
        user_to_unfollow = get_object_or_404(Profile, id=user_id)
        if request.user != user_to_unfollow:
            subscription = Subscription.objects.filter(follower=request.user, following=user_to_unfollow).first()

            if subscription:
                subscription.delete()
                request.user.following_count -= 1
                user_to_unfollow.followers_count -= 1
                request.user.save()
                user_to_unfollow.save()

        return HttpResponseRedirect(reverse('account:profile', args=[user_id]))

apps/account/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Login</title>
{% endblock %}

{% block content %}
    <div class="container">

        <div class="login border pt-4 pb-4 text-center">
            <h3 class="text-center"><img src="{% static 'logo.jpeg' %}" alt="logo" style="width: 200px;"></h3>

            <form action="{% url 'account:login' %}" method="post" class="text-center">
                {% csrf_token %}
                {% if has_error %}
                    <p class="form-error text-danger">Неверное имя пользователя или пароль</p>
                {% endif %}
                <div class="form-group mb-2">
                    <input type="text" name="username" id="username" placeholder="Username">
                </div>
                <div class="form-group mb-2">
                    <input type="password" name="password" id="password" placeholder="Password">
                </div>
                <button type="submit" class="btn btn-primary">Log in</button>
            </form>
        </div>
        <div class="signin border pb-3 pt-3 mt-3">
            <p class="text-center">Вы еще не зарегистрированы? <a href="{% url 'account:registration' %}"
                                                                  class="text-xenter">Зарегистрироваться</a>
            </p>
        </div>
    </div>
{% endblock %}

apps/account/templates/profile_view.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>{{ user_obj.username }}'s Profile</title>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="profile-header d-flex align-items-center mb-4">
            <div class="profile-avatar me-3">
                {% if user_obj.avatar %}
                    <img src="{{ user_obj.avatar.url }}" alt="pfp" class="img-fluid rounded-circle"
                         style="width: 150px; height: 150px;">
                {% else %}
                    <img src="{% static 'img.png' %}" alt="pfp" class="img-fluid rounded-circle"
                         style="width: 150px; height: 150px;">
                {% endif %}
            </div>
            <div>
                <h1 class="mb-2">{{ user_obj.username }}</h1>
                <h2 class="mb-2">{{ user_obj.first_name|default:'' }}</h2>
                <p class="bio">{{ user_obj.bio|default:'--' }}</p>
                <div class="d-flex justify-content-between mb-3">
                    <div class="text-center mx-3">
                        <h4>{{ posts_count }} posts</h4>
                    </div>
                    <div class="text-center mx-3">
                        <h4>{{ followers_count|default:0 }} followers</h4>
                    </div>
                    <div class="text-center mx-3">
                        <h4>{{ following_count }} following</h4>
                    </div>
                </div>
                {% if user_obj.username != request.user.username %}

                    {% if is_subscribed %}
                        <form action="{% url 'account:unsubscribe' user_obj.id %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-secondary">Unsubscribe</button>
                        </form>
                    {% else %}
                        <form action="{% url 'account:subscribe' user_obj.id %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-primary">Subscribe</button>
                        </form>
                    {% endif %}
                {% endif %}
            </div>
        </div>

        <h3>Posts</h3>
        <div class="container">
            <div class="row">
                {% for post in posts %}
                    <div class="col-md-4 mb-3">
                        <div class="card shadow-sm">
                            <div class="card-body">
                                {% if post.image %}
                                    <a href="{% url 'webapp:post_comment_view' post.id %}"><img src="{{ post.image.url }}" class="card-img-top mb-3"
                                                         alt="Post Image"
                                                         style="width: 100%; height: 300px; object-fit: cover;"></a>
                                {% else %}
                                    <img src="{% static 'img.png' %}" alt="No Image Available">
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% empty %}
                    <div class="col-12">
                        <p class="text-center">No posts available.</p>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

apps/account/templates/profiles_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Поиск пользователей</title>
{% endblock %}

{% block content %}
    <div class="container">
        <h1 class="my-4">Поиск пользователей</h1>

        <div class="list-group">
            {% if profiles %}
                {% for profile in profiles %}
                    <a href="{% url 'account:profile' profile.pk %}" class="list-group-item list-group-item-action d-flex align-items-center">
                        {% if profile.avatar %}
                            <img src="{{ profile.avatar.url }}" alt="pfp" class="img-thumbnail"
                                 style="width: 50px; height: 50px; border-radius: 50%; margin-right: 15px;">
                        {% else %}
                            <img src="{% static 'img.png' %}" alt="pfp" class="img-thumbnail"
                                 style="width: 50px; height: 50px; border-radius: 50%; margin-right: 15px;">
                        {% endif %}
                        <div>
                            <h5 class="mb-1">{{ profile.username }}</h5>
                            <small>{{ profile.first_name|default:"-" }}</small>
                            <small>{{ profile.email|default:"-" }}</small>
                        </div>
                    </a>
                {% endfor %}
            {% else %}
                <p>Пользователи не найдены.</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

apps/account/templates/registration.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    <title>Registration</title>
{% endblock %}

{% block content %}
    <div class="form border pt-4 pb-4">
        <h3 class="text-center"><img src="{% static 'logo.jpeg' %}" alt="logo" style="width: 150px;"></h3>
        <p class="text-center fs-6">Зарегистрируйтесь, чтобы увидеть <br> фотографии и видео от своих <br> друзей.</p>

        <form action="{% url 'account:registration' %}" method="post" enctype="multipart/form-data" class="text-center">
            {% csrf_token %}
            <div class="errors text-danger">
                {{ form.non_field_errors }}
                {{ form.username.errors }}
            </div>
        
            <div class="form-group mb-2">
                <input type="text" name="username" id="username" placeholder="Username" required
                       value="{{ form.username.value|default_if_none:'' }}">
            </div>
            {{ form.email.errors }}
            <div class="form-group mb-2">
                <input type="email" name="email" id="email" placeholder="Email" required
                       value="{{ form.email.value|default_if_none:'' }}">
            </div>
            {{ form.avatar.errors }}
            <div class="form-group mb-2">
                <input type="file" name="avatar" id="avatar" placeholder="Upload Avatar">
            </div>
            {{ form.password.errors }}
            <div class="form-group mb-2">
                <input type="password" name="password" id="password" placeholder="Password" required>
            </div>
            {{ form.password_confirm.errors }}
            <div class="form-group mb-2">
                <input type="password" name="password_confirm" id="password_confirm" placeholder="Confirm Password"
                       required>
            </div>
            {{ form.first_name.errors }}
            <div class="form-group mb-2">
                <input type="text" name="first_name" id="first_name" placeholder="First name"
                       value="{{ form.first_name.value|default_if_none:'' }}">
            </div>
            {{ form.bio.errors }}
            <div class="form-group mb-2">
                <input type="text" name="bio" id="bio" placeholder="Bio"
                       value="{{ form.bio.value|default_if_none:'' }}">
            </div>
            {{ form.phone_num.errors }}
            <div class="form-group mb-2">
                <input type="text" name="phone_num" id="phone_num" placeholder="Phone number"
                       value="{{ form.phone_num.value|default_if_none:'' }}">
            </div>
            {{ form.gender.errors }}
            <div class="form-group mb-2">
                <select name="gender" id="gender">
                    <option value="" disabled selected>Пол</option>
                    {% for key, value in form.gender.field.choices %}
                        <option value="{{ key }}"
                                {% if form.gender.value == key %}selected{% endif %}>{{ value }}</option>
                    {% endfor %}
                </select>
            </div>

            <button type="submit" class="btn btn-primary">Sign up</button>
        </form>
    </div>

    <div class="login border pb-3 pt-3 mt-3">
        <h6 class="text-center">Есть аккаунт? <a href="{% url 'account:login' %}">Войти</a></h6>
    </div>
{% endblock %}